version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.minimal
    container_name: mnr-client-backend
    restart: unless-stopped
    expose:
      - "3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CORS_ORIGIN=https://client.mnrlk.com
    labels:
      - "coolify.managed=true"
      - "coolify.name=mnr-client-backend"
      - "coolify.port=3001"
      - "coolify.healthcheck=/health"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.simple-stable
    container_name: mnr-client-frontend
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - VITE_API_URL=https://api.mnrlk.com
    depends_on:
      - backend
    labels:
      - "coolify.managed=true"
      - "coolify.name=mnr-client-frontend"
      - "coolify.port=80"
      - "coolify.healthcheck=/"
